### ISSUE TITLE
Improve action monitoring

### ISSUE THREAD

**Issue by trey0** [nasa/isaac#143]
A problem I've observed is that sometimes `command_astrobee` will get into a hanging state, but it's painful both to detect that condition and debug it:
- Detection is painful because the action node parent of `command_astrobee` will keep merrily ticking away despite its child hanging (the action node only watches for termination of the child, not progress).
- Debugging is painful because typically the best source of information is using `monitor_astrobee` to review the `command_astrobee` child's console output, but `monitor_astrobee` can't provide any of that console output if `command_astrobee` is unable to manage the socket I/O it relies on.

Some ideas about improvements that could help:
- For more accurate liveness detection:
  - Relevant `command_astrobee` children could print a heartbeat (i.e., any output at all) to stdout.
  - `command_astrobee` could detect child heartbeats through its socket management and propagate them as ROS messages.
  - The action node could subscribe to `command_astrobee` ROS heartbeats, detect missing heartbeats, and publish a warning in its console output and `send_feedback()` calls.
- For better debugging of hanging commands:
  - Review the status of `command_astrobee` logging of its child stdout. If not available already, record child stdout to a log file in addition to writing it to a socket. Make sure both the socket output and the log include not just the raw child stdout but also the child command that was run and the exit code once it completes. A main benefit of the log file is that it remains available even if `command_astrobee` socket management is hanging.
  - Consider improvements to how `command_astrobee` communicates its state to `monitor_astrobee`. For example, if this doesn't happen already, it could help for `command_astrobee` to delete its sockets on exit so `monitor_astrobee` can use their absence to report that `command_astrobee` isn't running (vs. running but hanging).
  - A late-connecting `monitor_astrobee` could start by reporting an excerpt from the latest log file before trying to read from the live socket (which may hang indefinitely without producing any useful info about what caused the hang).
  - `monitor_astrobee` could have a `--loop` flag such that it stays running indefinitely and auto-connects to new sockets from new `command_astrobee` calls (transitions between different calls can be emphasized in its output styling). With this option available, it could be convenient during ops to leave a persistent `monitor_astrobee` instance running for each robot using two tmux windows. In some ways, this operating mode could substitute for other improvements above if it diminishes concerns about properly servicing late-connecting instances of `monitor_astrobee`.

**Comment by bcoltin** [comment]
Not going to have time for this.
