### ISSUE TITLE
survey executor not accepting plan when one robot docked

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/isaac#161]
When we specify the initial configuration to be bumble in bay 6 and honey in berth2, I get the error at execution:

[ERROR] requirement not met: [(robot-at honey jem_bay7)]

the generated plan makes sense though:
0:      (move bumble jem_bay6 jem_bay5 jem_bay4)        [20]
20.001: (move bumble jem_bay5 jem_bay4 jem_bay3)        [20]
20.002: (undock honey berth2 jem_bay7 jem_bay6 jem_bay8)        [30]
40.002: (panorama bumble o0 jem_bay4)   [780]
50.003: (panorama honey o1 jem_bay7)    [780]
820.003:        (move bumble jem_bay4 jem_bay3 jem_bay2)        [20]
830.004:        (move honey jem_bay7 jem_bay6 jem_bay5) [20]
840.004:        (panorama bumble o1 jem_bay3)   [780]
850.005:        (panorama honey o2 jem_bay6)    [780]
1620.01:        (move bumble jem_bay3 jem_bay2 jem_bay1)        [20]
1630.01:        (move honey jem_bay6 jem_bay5 jem_bay4) [20]
1640.01:        (panorama bumble o2 jem_bay2)   [780]
1650.01:        (panorama honey o3 jem_bay5)    [780]
2420.01:        (move bumble jem_bay2 jem_bay1 jem_bay0)        [20]
2430.01:        (move honey jem_bay5 jem_bay6 jem_bay7) [20]
2440.01:        (panorama bumble o3 jem_bay1)   [780]
2450.01:        (move honey jem_bay6 jem_bay7 jem_bay8) [20]
2470.01:        (stereo honey o4 jem_bay7 jem_bay4 jem_bay3 jem_bay5)   [600]
3070.01:        (dock honey jem_bay7 berth2)    [90]
3220.01:        (stereo bumble o4 jem_bay1 jem_bay4 jem_bay3 jem_bay5)  [600]
3820.01:        (move bumble jem_bay1 jem_bay2 jem_bay3)        [20]
3840.01:        (move bumble jem_bay2 jem_bay3 jem_bay4)        [20]
3860.01:        (move bumble jem_bay3 jem_bay4 jem_bay5)        [20]
3880.01:        (move bumble jem_bay4 jem_bay5 jem_bay6)        [20]
3900.01:        (move bumble jem_bay5 jem_bay6 jem_bay7)        [20]
3920.01:        (move bumble jem_bay6 jem_bay7 jem_bay8)        [20]
3940.02:        (dock bumble jem_bay7 berth1)   [90]
[saved.txt](https://github.com/nasa/isaac/files/14872724/saved.txt)

**Comment by bcoltin** [comment]
Won't have time to fix this.
