### ISSUE TITLE
sci_cam_image timestamp updates

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/isaac#78]
- [x] Update APK to publish updated timestamp
- [x] Publish camera_info topic
- [x] Turn off bagfile image publishing by default in the sci_cam_image config (only publish camera_info)
- [x] Update all ISAAC survey recording profiles to turn on logging of the camera_info message in the logging profile
- [x] Change the inspection manager to subscribe to / trigger on the camera_info topic
- [x] Change panorama pipeline to use camera_info timestamps by default instead of image and look up the HLP-saved image files
- [x] Change mapping pipeline to use camera_info timestamps by default instead of image and look up the HLP-saved image files
- [x] @kbrowne15 update checkout recording profile check to not expect sci_cam image, but the sci_cam_info

**Comment by bcoltin** [comment]
@marinagmoreira needs to check post-processing scripts
